### ISSUE TITLE
Complete The README installation section

### ISSUE THREAD

**Issue by HarshKhandeparkar** [theblazecoders/smart-car-parking#30]
The README installation section is empty. It has to be completed.

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati would you like to work on this?

**Comment by Harshithpabbati** [comment]
Ok I will do it .

**Comment by HarshKhandeparkar** [comment]
Do you have labelling access now? @Harshithpabbati?

**Comment by Harshithpabbati** [comment]
No

**Comment by Harshithpabbati** [comment]
Add me as a collaborator.

**Comment by Harshithpabbati** [comment]
Then I will have all the things.

**Comment by HarshKhandeparkar** [comment]
You should have 🤔

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati please open a test pr.
