### ISSUE TITLE
Add Detailed Screen To App and booking functionality

### ISSUE THREAD

**Issue by sahil-patel6** [theblazecoders/smart-car-parking#42]

**Comment by HarshKhandeparkar** [comment]
Please add some description

**Comment by sahil-patel6** [comment]
Don't worry. There is no need btw I am only going to do so no need

**Comment by sahil-patel6** [comment]
this issue will be closed by tomorrow or day after tomorrow

**Comment by HarshKhandeparkar** [comment]
Btw, please add `Fixes #issuenumber` to the PR body so that the issue is
closed automatically as soon as the PR is merged. E.g. a PR with `Fixes #1`
in the body will close issue no. 1 upon merging. This keeps a good track of
history. Thanks.

**Comment by sahil-patel6** [comment]
Ok I will make note of that
